### ISSUE TITLE
Labeler does not handle landing zone without full control properly

### ISSUE THREAD

**Issue by jendab** [schubergphilis/awsenergylabelerlib#31]
The current labeler only works with either a single account, or a full landing zone.
The full landing zone assumes full control, access to AWS Organisations and one audit account where all findings are aggregated.

In some cases, this setup does not suffice. There are cases without full control of the landing zone, but there are multiple accounts which need to be labelled. These accounts also do send SecurityHub data to a central account.

We'd need a mechanism to get findings from an account, treat it like a zone, without the need for AWS Organisations. It should "opportunistically" gather all findings from SecurityHub, identify which accounts exist there and report on them.

**Comment by costastf** [comment]
MR https://github.com/schubergphilis/awsenergylabelerlib/pull/37 fixes for this with implementation of an Audit Zone object that does not require full organisations access.
