### ISSUE TITLE
BUG: Days Open does not get computed in a correct way

### ISSUE THREAD

**Issue by theodoorscholte** [schubergphilis/awsenergylabelerlib#38]
Finding.days_open returns -1 because of incorrect parsing of date fields. The following timestamps have to be supported: 
            "FirstObservedAt": "2022-10-14T09:46:26Z",
            "LastObservedAt": "2022-11-01T11:31:51Z",
            "CreatedAt": "2022-10-14T09:46:26Z",
            "UpdatedAt": "2022-11-01T11:31:51Z",
The timestamps are used for AWS Inspector-related findings.

**Comment by costastf** [comment]
fixed with v2.0.2
